"""initial_schema

Revision ID: 7e87d473fe48
Revises: 
Create Date: 2026-08-07 08:51:28.146969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e87d473fe48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=150), nullable=True),
    sa.Column('user_type', sa.Enum('admin', 'farmer', 'extension_worker', 'supervisor', name='usertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('extension_workers',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_ussd_pincode', sa.String(length=255), nullable=False),
    sa.Column('assigned_ward_name', sa.String(length=100), nullable=False),
    sa.Column('availability_status', sa.Enum('available', 'busy', 'offline', 'on_leave', name='workeravailabilitystatus'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farmers',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('primary_crop', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('farmer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('farmer_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.Enum('visit_request', 'advice_request', 'land_degradation_report', name='request_type'), nullable=False),
    sa.Column('ussd_input_text', sa.Text(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'resolved', 'cancelled', name='request_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['extension_workers.worker_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('field_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('related_request_id', sa.UUID(), nullable=True),
    sa.Column('sync_status', sa.Enum('pending_sync', 'synced', name='syncstatus'), server_default='pending_sync', nullable=False),
    sa.Column('issue_type', sa.Enum('land_degradation', 'pest_outbreak', 'crop_failure', name='issuetype'), nullable=True),
    sa.Column('report_details', sa.Text(), nullable=True),
    sa.Column('ussd_description', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.ForeignKeyConstraint(['related_request_id'], ['farmer_requests.request_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['extension_workers.worker_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('field_images',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['field_reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_images')
    op.drop_table('field_reports')
    op.drop_table('farmer_requests')
    op.drop_table('farmers')
    op.drop_table('extension_workers')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
